import {
  COMPLETION_TEMPLATE_KEY,
  COMPLETION_TEMPLATE_VERSION,
  type CompletionField,
  type CompletionGroup,
  type CompletionSection,
  type CompletionTemplateSchema,
} from './completionFormTypes';

const STATUS_NOTICE =
  'Pacific CCTV completion and handover record. This company form is not an official NSI certificate. Signatures captured here are drawn electronic signatures with an audit record, not certificate-backed digital signatures. Offline completion is not available.';

const VOLTAGE = [
  '12vDC',
  '24vAC',
  '24VDC',
  'POE 48v',
  'POC',
  'Dual voltage 12/24v',
  '12v + POE',
  '12v + POC',
];

const RECORDING_METHODS = ['Motion', 'Smart Analytics', 'Alarm Inputs', 'Constant'];
const TRIGGER_TYPES = ['Motion detector', 'Input Device Trigger', 'Access control system'];
const TECHNOLOGY = ['HD IP', 'HD TVI/AHD', 'ANALOGUE'];
const CABLE_TYPES = ['Coax', 'Cat cable using Baluns'];
const YES_NO = ['Yes', 'No'];
const YES_NO_NA = ['Yes', 'No', 'N/A'];
const YES_NA = ['Yes', 'N/A'];
const PSU_BATTERY = ['2.1ahr', '3.2ahr', '7ahr', '10ahr', '12ahr', '17ahr', 'Not Applicable'];
const STREAM_TYPES = ['RTSP', 'RTSP Authentication', 'HTTPS'];
const SPUR = ['Spur fitted with correct fuse', 'Fitted on plug top with correct fuse'];
const CHANGE_STATUS = ['No alterations', 'Alterations to specification'];
const DEFECT_STATUS = ['Open', 'In progress', 'Resolved', 'Accepted at handover'];

function field(partial: CompletionField): CompletionField {
  return partial;
}

function test(id: string, label: string, source: string, extras: Partial<CompletionField> = {}): CompletionField {
  return field({
    id,
    label,
    type: 'test_result',
    required: true,
    reasonWhen: ['fail', 'not_tested', 'not_applicable'],
    source,
    ...extras,
  });
}

export const CCTV_NCP104_GROUPS = {
  cameras: {
    id: 'cameras',
    title: 'Cameras',
    addLabel: 'Add camera',
    nameTemplate: 'Camera {camera_number} — {location}',
    identityFields: ['camera_number', 'location', 'camera_model', 'lens_type', 'camera_voltage', 'camera_technology'],
    source: 'PDF p5–8 Camera Repeat section',
    fields: [
      field({ id: 'camera_number', label: 'Camera number', type: 'text', required: true, source: 'PDF p5 Camera Number' }),
      field({ id: 'location', label: 'Location', type: 'text', required: true, source: 'PDF p5 Location' }),
      field({ id: 'camera_model', label: 'Camera model', type: 'text', required: true, source: 'PDF p5 Camera Model type' }),
      field({ id: 'lens_type', label: 'Lens type', type: 'text', source: 'PDF p5 lens Type' }),
      field({
        id: 'camera_voltage',
        label: 'Camera voltage',
        type: 'select',
        required: true,
        options: VOLTAGE,
        help: 'POE is power over Ethernet (IP systems). POC is power over coax (usually TVI or AHD).',
        source: 'PDF p6 Camera Voltage',
      }),
      field({
        id: 'recording_fps',
        label: 'Recording frames per second',
        type: 'number',
        required: true,
        unit: 'fps',
        min: 3,
        max: 30,
        step: 1,
        inputMode: 'numeric',
        source: 'PDF p6 Recording set up frames per second (slider replaced with number entry)',
      }),
      field({ id: 'recording_quality', label: 'Recording quality', type: 'text', unit: 'Mpx', help: 'Enter megapixels or the recorder quality setting.', source: 'PDF p6 Recording Quality (Mpxls)' }),
      field({
        id: 'recording_methods',
        label: 'Camera recording methods',
        type: 'multiselect',
        required: true,
        options: RECORDING_METHODS,
        source: 'PDF p6 Camera Recording method\'s',
      }),
      field({
        id: 'alarm_input_number',
        label: 'Alarm input number',
        type: 'number',
        unit: 'input',
        min: 0,
        max: 60,
        inputMode: 'numeric',
        required: true,
        showWhen: [{ field: 'recording_methods', op: 'includes', values: ['Alarm Inputs'] }],
        source: 'PDF p6–7 10.0 Alarm Input Number (shown when Alarm Inputs is selected)',
      }),
      field({
        id: 'input_trigger_type',
        label: 'Input trigger type',
        type: 'select',
        required: true,
        options: TRIGGER_TYPES,
        showWhen: [{ field: 'recording_methods', op: 'includes', values: ['Alarm Inputs'] }],
        source: 'PDF p7 10.1 Input trigger type',
      }),
      field({
        id: 'input_trigger_number',
        label: 'Input trigger number',
        type: 'text',
        required: true,
        showWhen: [{ field: 'input_trigger_type', op: 'in', values: ['Input Device Trigger', 'Access control system'] }],
        source: 'PDF p7 10.1.0',
      }),
      field({
        id: 'input_trigger_description',
        label: 'Input trigger description',
        type: 'text',
        required: true,
        showWhen: [{ field: 'input_trigger_type', op: 'in', values: ['Input Device Trigger', 'Access control system'] }],
        source: 'PDF p7 10.1.1',
      }),
      field({
        id: 'input_trigger_channel',
        label: 'Camera channel this input triggers',
        type: 'text',
        required: true,
        showWhen: [{ field: 'input_trigger_type', op: 'in', values: ['Input Device Trigger', 'Access control system'] }],
        source: 'PDF p7 10.1.2',
      }),
      field({
        id: 'camera_technology',
        label: 'Camera technology',
        type: 'select',
        required: true,
        options: TECHNOLOGY,
        source: 'PDF p8 CAMERA TECHNOLOGY',
      }),
      field({
        id: 'ip_address',
        label: 'Camera IP address',
        type: 'text',
        required: true,
        help: 'If the camera is plug and play, say so here.',
        showWhen: [{ field: 'camera_technology', op: 'eq', values: ['HD IP'] }],
        source: 'PDF p8 11.0',
      }),
      field({
        id: 'cable_length_m',
        label: 'Cable length',
        type: 'number',
        unit: 'm',
        min: 0,
        inputMode: 'decimal',
        showWhen: [{ field: 'camera_technology', op: 'eq', values: ['HD IP'] }],
        source: 'PDF p8 11.1',
      }),
      field({
        id: 'cable_tested',
        label: 'Network cable tested for wire map, short or open circuits, and terminated using T568B',
        type: 'test_result',
        required: true,
        reasonWhen: ['fail', 'not_tested', 'not_applicable'],
        showWhen: [{ field: 'camera_technology', op: 'eq', values: ['HD IP'] }],
        source: 'PDF p8 11.2 (Yes/No/N/A expanded to honest test results)',
      }),
      field({
        id: 'sd_card_fitted',
        label: 'Local SD card fitted',
        type: 'select',
        required: true,
        options: YES_NO_NA,
        showWhen: [{ field: 'camera_technology', op: 'eq', values: ['HD IP'] }],
        source: 'PDF p8 11.3',
      }),
      field({
        id: 'sd_card_capacity',
        label: 'SD card capacity',
        type: 'text',
        unit: 'GB',
        required: true,
        showWhen: [
          { field: 'camera_technology', op: 'eq', values: ['HD IP'] },
          { field: 'sd_card_fitted', op: 'eq', values: ['Yes'] },
        ],
        source: 'PDF p8 11.3.0',
      }),
      field({
        id: 'tvi_cable_type',
        label: 'Cable type',
        type: 'select',
        required: true,
        options: CABLE_TYPES,
        showWhen: [{ field: 'camera_technology', op: 'eq', values: ['HD TVI/AHD'] }],
        source: 'PDF p8 11.4',
      }),
      field({
        id: 'analogue_cable_type',
        label: 'Cable type',
        type: 'select',
        required: true,
        options: CABLE_TYPES,
        showWhen: [{ field: 'camera_technology', op: 'eq', values: ['ANALOGUE'] }],
        source: 'PDF p8 11.5',
      }),
    ],
  } satisfies CompletionGroup,
  recorders: {
    id: 'recorders',
    title: 'Recorders',
    addLabel: 'Add recorder',
    nameTemplate: 'Recorder — {recorder_model}',
    identityFields: ['recorder_model', 'channel_count'],
    source: 'PDF p9 Recorder Repeat section',
    fields: [
      field({ id: 'recorder_model', label: 'Recorder type / model', type: 'text', required: true, source: 'PDF p9 Recorder Type/Model' }),
      field({ id: 'firmware', label: 'Software / firmware version', type: 'text', source: 'PDF p10 Software/Firmware version no' }),
      field({ id: 'hdd_capacity_tb', label: 'Hard drive capacity', type: 'text', unit: 'TB', source: 'PDF p10 Hard Drive Capacity (Tb)' }),
      field({ id: 'channel_count', label: 'Number of channels', type: 'number', unit: 'channels', min: 1, inputMode: 'numeric', source: 'PDF p10 No of Channels' }),
      field({
        id: 'ups_fitted',
        label: 'Recorder fitted with UPS backup',
        type: 'select',
        required: true,
        options: YES_NO,
        source: 'PDF p10 Recorder fitted with UPS backup',
      }),
    ],
    nested: [
      {
        id: 'ups',
        title: 'UPS units',
        addLabel: 'Add UPS',
        nameTemplate: 'UPS — {location}',
        identityFields: ['location'],
        showWhen: [{ field: 'ups_fitted', op: 'eq', values: ['Yes'] }],
        source: 'PDF p10 UPS Repeat section (shown when UPS fitted = Yes)',
        fields: [
          field({
            id: 'battery_capacity',
            label: 'Battery capacity',
            type: 'text',
            required: true,
            source: 'PDF p10 2.0 Battery Capacity',
          }),
          field({
            id: 'location',
            label: 'Location',
            type: 'text',
            required: true,
            source: 'PDF p11 Location',
          }),
        ],
      },
    ],
  } satisfies CompletionGroup,
  psus: {
    id: 'psus',
    title: 'PSU and PoE switches',
    addLabel: 'Add PSU or switch',
    nameTemplate: 'PSU / switch — {location}',
    identityFields: ['location', 'voltage'],
    source: 'PDF p11 PSU details Repeat section',
    fields: [
      field({
        id: 'channel_count',
        label: 'Number of PSU / switch channels',
        type: 'number',
        unit: 'channels',
        min: 1,
        max: 32,
        inputMode: 'numeric',
        source: 'PDF p11 number of PSU / Switch channels (slider replaced with number entry)',
      }),
      field({ id: 'voltage', label: 'PSU / PoE switch voltage', type: 'select', options: VOLTAGE, source: 'PDF p11 PSU/POE Switch Voltage' }),
      field({ id: 'battery_capacity', label: 'Battery capacity', type: 'select', options: PSU_BATTERY, source: 'PDF p12 Battery Capacity' }),
      field({ id: 'location', label: 'PSU / PoE switch location', type: 'text', source: 'PDF p12 PSU/POE Switch Location' }),
    ],
  } satisfies CompletionGroup,
  userAccounts: {
    id: 'user_accounts',
    title: 'Manager and user accounts',
    addLabel: 'Add account',
    nameTemplate: 'User — {username}',
    identityFields: ['username'],
    source: 'PDF p13 User login details Repeat section',
    fields: [
      field({ id: 'username', label: 'NVR / DVR user name', type: 'text', required: true, sensitive: true, source: 'PDF p13 NVR/DVR user name' }),
      field({ id: 'password', label: 'NVR / DVR user password', type: 'text', required: true, sensitive: true, source: 'PDF p13 NVR/DVR User Password' }),
    ],
  } satisfies CompletionGroup,
  cloudStreams: {
    id: 'cloud_streams',
    title: 'Cloud streams',
    addLabel: 'Add stream',
    nameTemplate: 'Stream channel {channel_number}',
    identityFields: ['channel_number', 'stream_type'],
    showWhen: [{ field: 'has_cloud', op: 'eq', values: ['Yes'] }],
    source: 'PDF p15 Cloud storage stream info Repeat section',
    fields: [
      field({ id: 'channel_number', label: 'Channel number being streamed', type: 'text', source: 'PDF p15 Channel number being streamed' }),
      field({ id: 'stream_type', label: 'Stream type', type: 'select', options: STREAM_TYPES, source: 'PDF p16 TYPE (Authentification corrected to Authentication)' }),
      field({ id: 'ip_address', label: 'IP address for the streaming channel', type: 'text', source: 'PDF p16 IP address information for steaming channel' }),
      field({ id: 'upload_bandwidth', label: 'Channel upload bandwidth', type: 'text', unit: 'Mbps', source: 'PDF p16 Channel upload Bandwidth' }),
      field({ id: 'auth_username', label: 'User authentication user name', type: 'text', sensitive: true, source: 'PDF p16 User Authentication details : User name' }),
      field({ id: 'auth_password', label: 'User authentication password', type: 'text', sensitive: true, source: 'PDF p16 User Authentication details : Password' }),
    ],
  } satisfies CompletionGroup,
  interfaces: {
    id: 'interfaces',
    title: 'Interfaces',
    addLabel: 'Add interface',
    nameTemplate: '{system} — {details}',
    identityFields: ['system'],
    source: 'PDF p16–18 3rd Party Interface\'s (repeatable details when an interface is present)',
    fields: [
      field({ id: 'system', label: 'Interface', type: 'select', required: true, options: ['Guardian PA call system', 'Access control', 'Intruder alarm', 'Other'], source: 'PDF p16–18' }),
      field({ id: 'present', label: 'Interface present and tested', type: 'select', required: true, options: YES_NO_NA, source: 'PDF p16–18 Yes/No/N/A' }),
      field({
        id: 'details',
        label: 'Details and locations',
        type: 'textarea',
        required: true,
        showWhen: [{ field: 'present', op: 'eq', values: ['Yes'] }],
        source: 'PDF p16–18 1.0 / 2.0 / 3.0',
      }),
    ],
  } satisfies CompletionGroup,
  defects: {
    id: 'defects',
    title: 'Defects and outstanding work',
    addLabel: 'Add outstanding item',
    nameTemplate: '{location} — {description}',
    identityFields: ['location'],
    source: 'Not a blank table in the source PDF; required so Fail / Not tested items and incomplete work stay visible.',
    fields: [
      field({ id: 'description', label: 'Description', type: 'textarea', required: true }),
      field({ id: 'location', label: 'Equipment / location', type: 'text', required: true }),
      field({ id: 'evidence', label: 'Evidence or photo reference', type: 'text' }),
      field({ id: 'responsible', label: 'Responsible party', type: 'text' }),
      field({ id: 'status', label: 'Resolution status', type: 'select', required: true, options: DEFECT_STATUS }),
    ],
  } satisfies CompletionGroup,
  alterations: {
    id: 'alterations',
    title: 'Changes to specification',
    addLabel: 'Add change',
    nameTemplate: 'Change — {details}',
    identityFields: ['details'],
    showWhen: [{ field: 'ncp104_confirm', op: 'eq', values: ['Alterations to specification'] }],
    source: 'PDF p23 add detail for each alteration Repeat section',
    fields: [
      field({ id: 'details', label: 'Details of changes to specification', type: 'textarea', required: true, source: 'PDF p23 Details of Changes to specification' }),
    ],
  } satisfies CompletionGroup,
  trainees: {
    id: 'trainees',
    title: 'People trained',
    addLabel: 'Add person trained',
    nameTemplate: '{name}',
    identityFields: ['name'],
    showWhen: [{ field: 'users_trained', op: 'eq', values: ['Yes'] }],
    source: 'PDF p23 User trained Repeat section',
    fields: [
      field({ id: 'name', label: 'Name', type: 'text', required: true, customerVisible: true, source: 'PDF p23 Signature' }),
      field({ id: 'trained_on', label: 'Date trained', type: 'date', customerVisible: true, source: 'PDF p23 Date' }),
    ],
  } satisfies CompletionGroup,
};

const SECTIONS: CompletionSection[] = [
  {
    id: 'job',
    title: 'Job, customer and site',
    summary: 'Who the work is for and where it is.',
    customerVisible: true,
    source: 'PDF p1–4 Title page and Client and System Information',
    note: 'The source PDF listed live Simpro jobs from a SafetyCulture picker. This form uses the project job number instead of that account-specific list.',
    fields: [
      field({ id: 'job_number', label: 'Job number', type: 'text', required: true, customerVisible: true, source: 'PDF p2 Job Number (picker replaced with the project job number)' }),
      field({ id: 'site_address', label: 'Site address', type: 'textarea', required: true, customerVisible: true, source: 'PDF p2 Site Address' }),
      field({ id: 'client', label: 'Client', type: 'text', required: true, customerVisible: true, source: 'PDF p2 Client' }),
      field({ id: 'job_title', label: 'Job title', type: 'text', customerVisible: true, source: 'PDF p3 Job Title' }),
      field({ id: 'project_manager', label: 'Project manager', type: 'text', source: 'PDF p3 Project Manager' }),
      field({ id: 'engineer', label: 'Engineer', type: 'text', required: true, source: 'PDF p3 Engineer' }),
      field({ id: 'date_of_install', label: 'Date of install', type: 'date', required: true, customerVisible: true, source: 'PDF p4 Date of Install' }),
      field({ id: 'system_type', label: 'System type (make / model)', type: 'text', required: true, customerVisible: true, source: 'PDF p4 System Type (Make/Model)' }),
      field({
        id: 'scope_note',
        label: 'Imported quote quantities are proposed scope only. Confirm what was actually installed and tested.',
        type: 'note',
        customerVisible: true,
      }),
    ],
  },
  {
    id: 'cameras',
    title: 'Cameras and camera testing',
    summary: 'Each camera, how it records, and the tests that apply to it.',
    source: 'PDF p5–8',
    groups: [CCTV_NCP104_GROUPS.cameras],
  },
  {
    id: 'recorders',
    title: 'Recorders, storage and firmware',
    summary: 'Recorders, usable storage and any UPS on the recorder.',
    source: 'PDF p9–11',
    groups: [CCTV_NCP104_GROUPS.recorders],
  },
  {
    id: 'psus',
    title: 'UPS, power supplies and PoE switches',
    summary: 'Power supplies and PoE switches fitted on this job.',
    source: 'PDF p11–12',
    groups: [CCTV_NCP104_GROUPS.psus],
  },
  {
    id: 'images',
    title: 'Camera reference images',
    summary: 'Photographs of the approved as-fitted views.',
    customerVisible: true,
    source: 'PDF p12 AS FITTED IMAGES',
    fields: [
      field({
        id: 'images_taken',
        label: 'Snapshot of final as-fitted camera images taken',
        type: 'select',
        required: true,
        options: YES_NO,
        customerVisible: true,
        help: 'The source only offered Yes. This form also allows No so an unanswered or missing set of images is not treated as complete.',
        source: 'PDF p12 Snapshot of final as fitted Camera images',
      }),
      field({
        id: 'as_fitted_photos',
        label: 'Upload or take a photo of the as-fitted and approved images',
        type: 'photo',
        required: true,
        customerVisible: true,
        showWhen: [{ field: 'images_taken', op: 'eq', values: ['Yes'] }],
        source: 'PDF p12 1.0',
      }),
    ],
  },
  {
    id: 'credentials',
    title: 'Recorder and account access',
    summary: 'Record that access details were set up. Passwords stay out of the handover PDF.',
    source: 'PDF p12–13 System Login Information',
    note: 'User names, passwords and verification codes from the source PDF are stored only for the assigned engineer and office review. They are not written into the handover PDF, customer link, email or O&M download.',
    fields: [
      field({ id: 'admin_username', label: 'NVR / DVR admin user name', type: 'text', required: true, sensitive: true, source: 'PDF p12 NVR/DVR Admin User name' }),
      field({ id: 'admin_password', label: 'NVR / DVR admin password', type: 'text', required: true, sensitive: true, source: 'PDF p13 NVR/DVR Admin Password' }),
      field({
        id: 'credentials_handed_over',
        label: 'Access details were handed over separately',
        type: 'select',
        required: true,
        options: YES_NO,
        help: 'Do not put live passwords in the customer pack. Record who received them and when.',
      }),
      field({
        id: 'credential_recipient',
        label: 'Received by',
        type: 'text',
        required: true,
        showWhen: [{ field: 'credentials_handed_over', op: 'eq', values: ['Yes'] }],
      }),
      field({
        id: 'credential_handover_date',
        label: 'Date handed over',
        type: 'date',
        required: true,
        showWhen: [{ field: 'credentials_handed_over', op: 'eq', values: ['Yes'] }],
      }),
    ],
    groups: [CCTV_NCP104_GROUPS.userAccounts],
  },
  {
    id: 'remote',
    title: 'Remote access',
    summary: 'App or software viewing, when the customer has it.',
    source: 'PDF p13–14 App/software information',
    fields: [
      field({
        id: 'has_remote',
        label: 'Customer has app or software remote viewing',
        type: 'select',
        required: true,
        options: YES_NO_NA,
        source: 'PDF p13 Does the customer have App/software remote viewing facilities',
      }),
      field({ id: 'user_id', label: 'User ID', type: 'text', sensitive: true, required: true, showWhen: [{ field: 'has_remote', op: 'eq', values: ['Yes'] }], source: 'PDF p14 8.0' }),
      field({ id: 'user_password', label: 'User password', type: 'text', sensitive: true, required: true, showWhen: [{ field: 'has_remote', op: 'eq', values: ['Yes'] }], source: 'PDF p14 8.1' }),
      field({ id: 'fen_name', label: 'FEN / system name', type: 'text', showWhen: [{ field: 'has_remote', op: 'eq', values: ['Yes'] }], source: 'PDF p14 8.2' }),
      field({ id: 'verification_code', label: 'Unit verification code (Hikvision systems)', type: 'text', sensitive: true, showWhen: [{ field: 'has_remote', op: 'eq', values: ['Yes'] }], source: 'PDF p14 8.3' }),
      field({ id: 'unit_serial', label: 'Unit serial number', type: 'text', showWhen: [{ field: 'has_remote', op: 'eq', values: ['Yes'] }], source: 'PDF p14 8.4' }),
      field({ id: 'unit_model', label: 'Unit model number', type: 'text', showWhen: [{ field: 'has_remote', op: 'eq', values: ['Yes'] }], source: 'PDF p14 8.5' }),
      field({ id: 'pc_os', label: 'PC operating system', type: 'text', showWhen: [{ field: 'has_remote', op: 'eq', values: ['Yes'] }], source: 'PDF p15 8.6' }),
    ],
  },
  {
    id: 'cloud',
    title: 'Cloud recording',
    summary: 'Remote cloud storage, when it is part of this install.',
    source: 'PDF p15–16 Cloud Storage set-up',
    fields: [
      field({
        id: 'has_cloud',
        label: 'System has remote cloud storage set up',
        type: 'select',
        required: true,
        options: YES_NO_NA,
        source: 'PDF p15 Does the system have remote cloud storage set-up',
      }),
      field({
        id: 'bandwidth_ok',
        label: 'Internet connection has the required upload bandwidth for the cameras being streamed',
        type: 'select',
        required: true,
        options: YES_NO,
        showWhen: [{ field: 'has_cloud', op: 'eq', values: ['Yes'] }],
        source: 'PDF p15 1.0',
      }),
      field({
        id: 'upload_bandwidth',
        label: 'Measured upload bandwidth',
        type: 'text',
        unit: 'Mbps',
        required: true,
        showWhen: [
          { field: 'has_cloud', op: 'eq', values: ['Yes'] },
          { field: 'bandwidth_ok', op: 'eq', values: ['Yes'] },
        ],
        source: 'PDF p15 1.0.0 (hear corrected to here)',
      }),
    ],
    groups: [CCTV_NCP104_GROUPS.cloudStreams],
  },
  {
    id: 'interfaces',
    title: 'Interfaces with other systems',
    summary: 'PA, access control and intruder links, where they exist.',
    source: 'PDF p16–18',
    groups: [CCTV_NCP104_GROUPS.interfaces],
  },
  {
    id: 'inspection',
    title: 'Inspection and commissioning checks',
    summary: 'Required site and system checks. Do not mark a check as passed unless it was done.',
    source: 'PDF p18–22 Handover checklist',
    note: 'The source mostly offered Yes or N/A. This record uses Pass, Fail, Not tested and Not applicable so unanswered and failed checks stay visible.',
    fields: [
      test('cabling_bs7671', 'Cabling has been carried out in line with wiring regulations (BS 7671), including metal clips or ties supporting cable along the entire route in the event of a fire', 'PDF p18'),
      test('cables_labelled', 'All cables labelled at termination points (recorder, remote switchgear and PSUs)', 'PDF p18'),
      test('time_auto', 'Date and time set to auto-update with DST, or an NTP server is used', 'PDF p18'),
      test('monitoring_ok', 'Operation of all monitoring, switching, multiplexing and recording equipment is satisfactory', 'PDF p18'),
      test('analytics_ok', 'Video motion detection and/or video analytic detection is triggering the CCTV system correctly', 'PDF p19'),
      test('signs_installed', 'Appropriate “CCTV in operation” signs have been installed', 'PDF p19'),
      field({
        id: 'sign_photos',
        label: 'Photograph of installed signs',
        type: 'photo',
        required: true,
        showWhen: [{ field: 'signs_installed', op: 'eq', values: ['pass'] }],
        source: 'PDF p19 6.0 Provide Photo of installed Signs',
      }),
      test('ups_standby', 'If standby UPS power is fitted, the system continues to operate correctly to specification when the mains supply is disconnected', 'PDF p19'),
      test('ptz_ok', 'All camera PTZ operations work correctly (pan, tilt, zoom, focus)', 'PDF p19'),
      test('motorised_ok', 'All motorised camera functions operate correctly (menu access, zoom, focus) under all light conditions', 'PDF p19'),
      test('lenses_as_spec', 'All cameras and lenses fitted in each location are correct as per the specification', 'PDF p19 (lenes corrected to lenses)'),
      test('monitor_ok', 'The correct monitor type has been fitted so the entire camera picture can be viewed', 'PDF p20'),
      test('retention_31', '31 days recording can be achieved, or as detailed in the specification', 'PDF p20 (achived corrected to achieved)'),
      test('night_images', 'Night images are clear and focused', 'PDF p20'),
      test('reference_images', 'As-installed reference images of each camera taken', 'PDF p20 (referance corrected to reference)'),
      test('lighting_ok', 'Any supplementary lighting is working correctly (infrared lamps or LED lights)', 'PDF p20 (suplimentary / Infa red corrected)'),
      test('segregation', 'All high voltage 100 V+ and low voltage cables are segregated', 'PDF p20'),
      test('movable_warnings', 'Warning signs are in place if there is a chance movable cameras may impact persons or property if in close proximity', 'PDF p20 (Moveable corrected to movable)'),
      test('site_tidy', 'All surplus material and equipment is cleared from site and the customer’s premises have been left tidy', 'PDF p21 (suplus corrected to surplus)'),
      field({
        id: 'depart_photos',
        label: 'Photograph of the work area when departing',
        type: 'photo',
        required: true,
        showWhen: [{ field: 'site_tidy', op: 'eq', values: ['pass'] }],
        source: 'PDF p21 18.0',
      }),
      field({
        id: 'psu_supply',
        label: 'PSUs connected to a spur with an adequate fuse. If on a plug top, make a note on this handover.',
        type: 'select',
        required: true,
        options: SPUR,
        source: 'PDF p22 (adequete corrected to adequate)',
      }),
      field({
        id: 'gdpr_informed',
        label: 'Customer informed that any documents left on site may contain personal information about their security and should be stored securely, as per ISO 27001 and UK GDPR policy',
        type: 'select',
        required: true,
        options: YES_NO,
        customerVisible: true,
        source: 'PDF p22 (there/stores corrected to their/stored)',
      }),
    ],
  },
  {
    id: 'defects',
    title: 'Changes, defects and outstanding work',
    summary: 'Agreed changes and anything still open.',
    customerVisible: true,
    source: 'PDF p22–23 Amendments to specification, plus outstanding-work records required for honest handover',
    fields: [
      field({
        id: 'ncp104_confirm',
        label: 'Confirm that the requirements of NCP 104 and all other relevant requirements are met, and that any changes to the specification are agreed and documented',
        type: 'select',
        required: true,
        options: CHANGE_STATUS,
        customerVisible: true,
        help: 'This is the company’s recorded confirmation from the source form. It is not an official NSI certificate. The applicable NCP 104 edition still needs a controlled wording check.',
        source: 'PDF p22',
      }),
    ],
    groups: [CCTV_NCP104_GROUPS.alterations, CCTV_NCP104_GROUPS.defects],
  },
  {
    id: 'training',
    title: 'Customer training and documents',
    summary: 'Who was trained and what was left on site.',
    customerVisible: true,
    source: 'PDF p23 Completion certificate / User\'s trained',
    fields: [
      field({ id: 'users_trained', label: 'Users trained', type: 'select', required: true, options: YES_NO, customerVisible: true, source: 'PDF p23 User\'s trained' }),
      field({ id: 'user_guide', label: 'User guide supplied', type: 'select', required: true, options: YES_NO_NA, customerVisible: true, source: 'PDF p23 User guide supplied' }),
      field({
        id: 'app_advice',
        label: 'If using an app, consult the manufacturer’s website regularly so device compatibility is maintained. The user is responsible for keeping the app and device up to date. The company does not accept responsibility for third-party applications and issues arising from their use.',
        type: 'note',
        customerVisible: true,
        source: 'PDF p23 Note 1',
      }),
      field({
        id: 'remote_unset_advice',
        label: 'If using a remote device to remotely set or unset an intruder alarm system, whenever a premise is unattended but its intruder alarm system is not fully set, any related insurance cover might be inoperative. For advice, consult the insurer.',
        type: 'note',
        customerVisible: true,
        source: 'PDF p23 Note 2 (intruder-alarm wording preserved from the CCTV source form)',
      }),
    ],
    groups: [CCTV_NCP104_GROUPS.trainees],
  },
  {
    id: 'engineer',
    title: 'Engineer declaration',
    summary: 'The engineer signs the technical record for this revision.',
    source: 'PDF p24 Engineer Name & Signature',
    fields: [
      field({
        id: 'declaration',
        label: 'I confirm that the cameras, recorders, tests, photographs and outstanding items recorded on this revision are a true record of the work I completed. This is a drawn electronic signature with an audit record, not a qualified digital signature.',
        type: 'declaration',
        required: true,
      }),
      field({ id: 'name', label: 'Engineer full name', type: 'text', required: true, source: 'PDF p24 Engineer Name' }),
      field({ id: 'company', label: 'Company', type: 'text', required: true }),
      field({ id: 'role', label: 'Role', type: 'text', required: true }),
      field({ id: 'signature', label: 'Engineer signature', type: 'signature', required: true, source: 'PDF p24 Engineer Name & Signature' }),
    ],
  },
  {
    id: 'customer',
    title: 'Customer handover acknowledgement',
    summary: 'The customer acknowledges handover and any stated exceptions.',
    customerVisible: true,
    source: 'PDF p24 Final sign off',
    note: 'The customer acknowledges handover, training, cleanliness, operational state, view-maintenance responsibility, data-protection awareness and the listed exceptions. The customer does not certify engineering tests, regulatory compliance or matters outside their responsibility.',
    fields: [
      field({
        id: 'handover_points',
        label: 'The customer is asked to confirm: they accept the installed system after a demonstration that meets their requirements; the site was left clean and tidy; the system was left operational; tree and environmental maintenance that could affect camera views is the user’s responsibility; camera views should remain as agreed and any change should be logged; the installing company may retain access information needed for maintenance; they are aware of DPA and UK GDPR requirements.',
        type: 'note',
        customerVisible: true,
        source: 'PDF p24 Final sign off bullets',
      }),
      field({
        id: 'payment_note',
        label: 'The source form also asked the customer to confirm that payment in full will be made as per agreement. That payment sentence is contractual. It is shown here for review and is not treated as a technical commissioning result.',
        type: 'note',
        customerVisible: true,
        source: 'PDF p24 Payment in full will be made as per agreement',
      }),
      field({
        id: 'follow_up_note',
        label: 'Following completion of the works the following will be issued within 30 days: an NSI Certificate of Compliance, issued separately from this record, and a customer satisfaction survey. This form is not that certificate.',
        type: 'note',
        customerVisible: true,
        source: 'PDF p25',
      }),
      field({
        id: 'accepted',
        label: 'I acknowledge handover of the system described in this summary, including the listed training, documents, limitations and outstanding items. I am not certifying the engineer’s tests or regulatory compliance.',
        type: 'declaration',
        required: true,
        customerVisible: true,
      }),
      field({ id: 'name', label: 'Customer or customer representative name', type: 'text', required: true, customerVisible: true, source: 'PDF p24 Customer/Customer\'s representative\'s Name' }),
      field({ id: 'role', label: 'Role', type: 'text', required: true, customerVisible: true }),
      field({ id: 'signature', label: 'Customer signature', type: 'signature', required: true, customerVisible: true, source: 'PDF p24 Signature' }),
      field({ id: 'handover_date', label: 'Handover date', type: 'date', required: true, customerVisible: true, source: 'PDF p24 Handover Date' }),
      field({
        id: 'correction_comment',
        label: 'Request a correction / not ready to sign',
        type: 'textarea',
        customerVisible: true,
        help: 'Use this instead of signing if something is wrong or not ready.',
      }),
    ],
  },
];

export const CCTV_NCP104_SCHEMA: CompletionTemplateSchema = {
  key: COMPLETION_TEMPLATE_KEY,
  version: COMPLETION_TEMPLATE_VERSION,
  title: 'Pacific CCTV completion and handover',
  statusNotice: STATUS_NOTICE,
  sections: SECTIONS,
  reviewFlags: [
    {
      id: 'ncp104_edition',
      source: 'PDF p22 Confirm that the Requirements of NCP 104…',
      wording: 'Confirm that the requirements of NCP 104 and all other relevant requirements are met.',
      reason: 'The applicable NCP 104 edition and controlled declaration wording still need verification. This form is not an official NSI certificate.',
    },
    {
      id: 'payment_clause',
      source: 'PDF p24 Payment in full will be made as per agreement.',
      wording: 'Payment in full will be made as per agreement.',
      reason: 'Contractual payment wording. Shown as a review note, not as a technical test result.',
    },
    {
      id: 'intruder_insurance_note',
      source: 'PDF p23 Note 2',
      wording: 'Remote set/unset insurance warning for an intruder alarm.',
      reason: 'Preserved from the CCTV source form even though it refers to an intruder system.',
    },
    {
      id: 'nsi_certificate_followup',
      source: 'PDF p25 NSI Certificate of Compliance will be issued within 30 days',
      wording: 'NSI Certificate of Compliance will be issued within 30 days.',
      reason: 'Company process note. This record is not that certificate.',
    },
  ],
};

export const CCTV_NCP104_SOURCE_TRACE: Array<{ source: string; implemented: string }> = [
  { source: 'PDF p1 title / commissioning, compliance, handover', implemented: 'Document title and status notice. NCP 104 is not treated as a certificate.' },
  { source: 'PDF p2 job picker + site + client', implemented: 'job.job_number, site_address, client. Live SafetyCulture job list not copied.' },
  { source: 'PDF p3 job title, PM, engineer', implemented: 'job.job_title, project_manager, engineer' },
  { source: 'PDF p4 date of install, system type', implemented: 'job.date_of_install, system_type' },
  { source: 'PDF p5–8 camera repeat + conditionals 10.x and 11.x', implemented: 'cameras group with voltage, FPS number, recording methods, alarm, IP, SD, cable type' },
  { source: 'PDF p9–11 recorder + UPS repeat', implemented: 'recorders group with nested ups when ups_fitted = Yes' },
  { source: 'PDF p11–12 PSU / PoE repeat', implemented: 'psus group with channel number 1–32' },
  { source: 'PDF p12 as-fitted images', implemented: 'images.images_taken + as_fitted_photos' },
  { source: 'PDF p12–13 admin and user passwords', implemented: 'credentials section, marked sensitive and excluded from PDF/customer pack' },
  { source: 'PDF p13–15 remote app 8.0–8.6', implemented: 'remote section, shown when has_remote = Yes' },
  { source: 'PDF p15–16 cloud 1.0 / streams', implemented: 'cloud section + cloud_streams group' },
  { source: 'PDF p16–18 Guardian / access / intruder', implemented: 'interfaces group' },
  { source: 'PDF p18–22 inspection checklist + photos 6.0 and 18.0', implemented: 'inspection test_result fields + sign_photos + depart_photos' },
  { source: 'PDF p22 PSU spur / GDPR', implemented: 'inspection.psu_supply, gdpr_informed' },
  { source: 'PDF p22–23 NCP 104 / alterations', implemented: 'defects.ncp104_confirm + alterations group; edition flagged' },
  { source: 'PDF p23 training and user guide', implemented: 'training.users_trained, trainees, user_guide' },
  { source: 'PDF p23 notes 1–2', implemented: 'training.app_advice, remote_unset_advice' },
  { source: 'PDF p24–25 customer and engineer signatures + 30-day follow-up', implemented: 'engineer and customer sections; payment and NSI certificate flagged' },
];
