-- Replace the default Intruder Alarm document set with IA01–IA14.
-- Customer signs IA07 routinely; extra customer acceptance only on limitation/change forms.
-- Technical measurements and tests remain engineer / reviewer sign-off.
-- These company forms are not an NSI certificate.

UPDATE handover_document_definitions
SET is_active = false,
    updated_at = now()
WHERE type_key = 'intruder_alarm'
  AND document_id IN (
    'handover_intruder',
    'handover_intruder_record',
    'intruder_zone_list',
    'intruder_bell_strobe_test',
    'intruder_keyholder_confirmation',
    'intruder_customer_training'
  );

INSERT INTO handover_document_definitions
  (document_id, type_key, title, description, icon_key, sc_enabled, sc_template_id, required, upload_only, multi, display_order, is_active)
VALUES
  ('ia01_as_fitted', 'intruder_alarm', 'IA01 As-fitted system record', 'Installed equipment schedule. Engineer verification. Quoted qty is not installed proof.', 'file', true, 'ia01_as_fitted', true, false, false, 10, true),
  ('ia02_readings', 'intruder_alarm', 'IA02 Parameters and electrical readings', 'Device, supply and settings readings. Engineer sign-off only.', 'clipboard', true, 'ia02_readings', false, false, false, 20, true),
  ('ia03_commissioning', 'intruder_alarm', 'IA03 Commissioning and verification', 'Commissioning checks and tests. Engineer sign-off only.', 'clipboard', true, 'ia03_commissioning', false, false, false, 30, true),
  ('ia04_arc', 'intruder_alarm', 'IA04 ARC signalling verification', 'End-to-end signalling tests. Engineer sign-off only.', 'clipboard', true, 'ia04_arc', false, false, false, 40, true),
  ('ia05_changes', 'intruder_alarm', 'IA05 Changes and remedial actions', 'Design changes, defects and limitations. Customer signs only if a change or limitation needs agreement.', 'file', true, 'ia05_changes', false, false, false, 50, true),
  ('ia06_training', 'intruder_alarm', 'IA06 Customer demonstration and training', 'Trainer record of demonstration. Customer acknowledgement is on IA07.', 'graduation', true, 'ia06_training', false, false, false, 60, true),
  ('ia07_handover', 'intruder_alarm', 'IA07 Completion and handover acceptance', 'The routine customer signature. Acknowledges demonstration, documents and operating status.', 'award', true, 'ia07_handover', true, false, false, 70, true),
  ('ia08_log', 'intruder_alarm', 'IA08 System history and event log', 'Activations, faults and visits. No signature required.', 'file', true, 'ia08_log', false, false, false, 80, true),
  ('ia09_support', 'intruder_alarm', 'IA09 Maintenance and support information', 'Service contacts and warranty. Issued by the engineer; receipt is on IA07.', 'file', true, 'ia09_support', false, false, false, 90, true),
  ('ia10_release', 'intruder_alarm', 'IA10 O&M index and technical release', 'Document completeness and company technical release. Reviewer sign-off.', 'clipboard', true, 'ia10_release', false, false, false, 100, true),
  ('ia11_takeover', 'intruder_alarm', 'IA11 Takeover survey and condition record', 'Inherited installation survey. Customer signs only if the takeover is conditional or limited.', 'clipboard', true, 'ia11_takeover', false, false, false, 110, true),
  ('ia12_upgrade', 'intruder_alarm', 'IA12 Upgrade and extension record', 'Change scope and retesting. Customer signs only for design changes or limitations.', 'clipboard', true, 'ia12_upgrade', false, false, false, 120, true),
  ('ia13_transfer', 'intruder_alarm', 'IA13 Maintenance and monitoring transfer', 'Provider transfer. Customer signs only if there is an interruption or limitation.', 'file', true, 'ia13_transfer', false, false, false, 130, true),
  ('ia14_maintenance', 'intruder_alarm', 'IA14 Maintenance and corrective work', 'Visit record. Engineer sign-off only.', 'clipboard', true, 'ia14_maintenance', false, false, false, 140, true),
  ('nsi_certificate_intruder', 'intruder_alarm', 'NSI Certificate of Compliance', 'Official issued certificate — attach separately. Not generated by these forms.', 'shield', false, null, false, true, false, 150, true)
ON CONFLICT (document_id) DO UPDATE SET
  type_key = EXCLUDED.type_key,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  icon_key = EXCLUDED.icon_key,
  sc_enabled = EXCLUDED.sc_enabled,
  sc_template_id = EXCLUDED.sc_template_id,
  required = EXCLUDED.required,
  upload_only = EXCLUDED.upload_only,
  multi = EXCLUDED.multi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = now();
