-- Replace separate CV/IA sheets with one SDP plus IA01, CC01 and AC01 standalone records.

UPDATE handover_document_definitions
SET is_active = false,
    updated_at = now()
WHERE document_id IN (
  'ia01_as_fitted', 'ia02_readings', 'ia03_commissioning', 'ia04_arc', 'ia05_changes', 'ia06_training',
  'ia07_handover', 'ia08_log', 'ia09_support', 'ia10_release', 'ia11_takeover', 'ia12_upgrade',
  'ia13_transfer', 'ia14_maintenance', 'ia15_acceptance',
  'cv01_as_fitted', 'cv02_cameras', 'cv03_commissioning', 'cv04_recording', 'cv05_monitoring',
  'cv06_changes', 'cv07_training', 'cv08_handover', 'cv09_log', 'cv10_support', 'cv11_release',
  'cv12_takeover', 'cv13_upgrade', 'cv14_maintenance', 'cv15_acceptance', 'cv16_survey',
  'handover_ac', 'ac_door_schedule', 'ac_controller_configuration', 'ac_reader_test_sheet', 'ac_customer_training',
  'handover_intruder', 'handover_cctv', 'camera_schedule', 'cctv_commissioning_sheet', 'nvr_dvr_configuration',
  'cctv_customer_training'
);

INSERT INTO handover_document_definitions
  (document_id, type_key, title, description, icon_key, sc_enabled, sc_template_id, required, upload_only, multi, display_order, is_active)
VALUES
  ('sdp', 'project_wide', 'System Design Proposal (SDP)', 'Editable proposed or as-fitted scope from the Simpro job. Signatures bind this revision only.', 'file', true, 'sdp', true, false, false, 5, true),
  ('ia01_completion', 'intruder_alarm', 'IA01 Intruder alarm completion and handover', 'One standalone NCP 120 record. Engineer and customer sign on this sheet only.', 'clipboard', true, 'ia01_completion', true, false, false, 20, true),
  ('cc01_completion', 'cctv', 'CC01 CCTV completion and handover', 'One standalone NCP 104 record. Engineer and customer sign on this sheet only.', 'clipboard', true, 'cc01_completion', true, false, false, 20, true),
  ('ac01_completion', 'access_control', 'AC01 Access control completion and handover', 'One standalone NCP 109 record. Engineer and customer sign on this sheet only.', 'clipboard', true, 'ac01_completion', true, false, false, 20, true),
  ('nsi_certificate_cctv', 'cctv', 'NSI Certificate of Compliance', 'Official issued certificate — attach separately. Not generated by these forms.', 'shield', false, null, false, true, false, 30, true),
  ('nsi_certificate_intruder', 'intruder_alarm', 'NSI Certificate of Compliance', 'Official issued certificate — attach separately. Not generated by these forms.', 'shield', false, null, false, true, false, 30, true),
  ('nsi_certificate_ac', 'access_control', 'NSI Certificate of Compliance', 'Official issued certificate — attach separately. Not generated by these forms.', 'shield', false, null, false, true, false, 30, true)
ON CONFLICT (document_id) DO UPDATE SET
  type_key = EXCLUDED.type_key,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  icon_key = EXCLUDED.icon_key,
  sc_enabled = EXCLUDED.sc_enabled,
  sc_template_id = EXCLUDED.sc_template_id,
  required = EXCLUDED.required,
  upload_only = EXCLUDED.upload_only,
  multi = EXCLUDED.multi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = now();
