-- Replace the default CCTV document set with CV01–CV16.
-- Customer signs CV08 routinely; extra customer acceptance only on CV15.
-- Technical measurements and tests remain engineer / reviewer sign-off.
-- CV00 is the pack guide and is not a fillable form.
-- CV05 is used only for remotely monitored / detector-activated / BS 8418 systems.
-- These company forms are not an NSI certificate.

UPDATE handover_document_definitions
SET is_active = false,
    updated_at = now()
WHERE type_key = 'cctv'
  AND document_id IN (
    'handover_cctv',
    'cctv_commissioning_sheet',
    'camera_schedule',
    'nvr_dvr_configuration',
    'cctv_customer_training'
  );

INSERT INTO handover_document_definitions
  (document_id, type_key, title, description, icon_key, sc_enabled, sc_template_id, required, upload_only, multi, display_order, is_active)
VALUES
  ('cv01_as_fitted', 'cctv', 'CV01 As-fitted system record', 'Installed camera and recorder schedule. Engineer verification. Quoted qty is not installed proof.', 'file', true, 'cv01_as_fitted', true, false, false, 10, true),
  ('cv02_cameras', 'cctv', 'CV02 Camera and infrastructure record', 'Image, siting, network and power results. Engineer sign-off only.', 'clipboard', true, 'cv02_cameras', false, false, false, 20, true),
  ('cv03_commissioning', 'cctv', 'CV03 Commissioning and verification', 'Commissioning checks and tests. Engineer sign-off only.', 'clipboard', true, 'cv03_commissioning', false, false, false, 30, true),
  ('cv04_recording', 'cctv', 'CV04 Recording and export verification', 'Retention, playback and export tests. Engineer sign-off; customer results on CV08.', 'clipboard', true, 'cv04_recording', false, false, false, 40, true),
  ('cv05_monitoring', 'cctv', 'CV05 Remote monitoring verification', 'Use only for remotely monitored / detector-activated / BS 8418 systems. Engineer sign-off only.', 'clipboard', true, 'cv05_monitoring', false, false, false, 50, true),
  ('cv06_changes', 'cctv', 'CV06 Changes and remedial actions', 'Design changes, defects and limitations. Reviewer sign-off. Customer agreement is on CV15 where required.', 'file', true, 'cv06_changes', false, false, false, 60, true),
  ('cv07_training', 'cctv', 'CV07 Customer demonstration and training', 'Trainer record of demonstration. Customer acknowledgement is on CV08.', 'graduation', true, 'cv07_training', false, false, false, 70, true),
  ('cv08_handover', 'cctv', 'CV08 Completion and handover acceptance', 'The routine customer signature. Acknowledges demonstration, documents and operating status.', 'award', true, 'cv08_handover', true, false, false, 80, true),
  ('cv09_log', 'cctv', 'CV09 System history and event log', 'Activations, faults and visits. No signature required.', 'file', true, 'cv09_log', false, false, false, 90, true),
  ('cv10_support', 'cctv', 'CV10 Maintenance and support information', 'Service contacts and warranty. Issued by the engineer; receipt is on CV08.', 'file', true, 'cv10_support', false, false, false, 100, true),
  ('cv11_release', 'cctv', 'CV11 O&M index and technical release', 'Document completeness and company technical release. Reviewer sign-off.', 'clipboard', true, 'cv11_release', false, false, false, 110, true),
  ('cv12_takeover', 'cctv', 'CV12 Takeover survey and condition record', 'Inherited installation survey. Customer signs CV15 only if the takeover is conditional or limited.', 'clipboard', true, 'cv12_takeover', false, false, false, 120, true),
  ('cv13_upgrade', 'cctv', 'CV13 Upgrade and extension record', 'Change scope and retesting. Customer signs CV15 only for design changes or limitations.', 'clipboard', true, 'cv13_upgrade', false, false, false, 130, true),
  ('cv14_maintenance', 'cctv', 'CV14 Maintenance and corrective work', 'Visit record. Engineer sign-off only.', 'clipboard', true, 'cv14_maintenance', false, false, false, 140, true),
  ('cv15_acceptance', 'cctv', 'CV15 Customer acceptance of change or limitation', 'Extra customer signature only for design changes, reduced coverage or incomplete tests.', 'award', true, 'cv15_acceptance', false, false, false, 150, true),
  ('cv16_survey', 'cctv', 'CV16 Survey and test plan', 'Planned survey and tests. Engineer and reviewer; do not repeat CV08/CV15 signatures.', 'clipboard', true, 'cv16_survey', false, false, false, 160, true),
  ('nsi_certificate_cctv', 'cctv', 'NSI Certificate of Compliance', 'Official issued certificate — attach separately. Not generated by these forms.', 'shield', false, null, false, true, false, 170, true)
ON CONFLICT (document_id) DO UPDATE SET
  type_key = EXCLUDED.type_key,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  icon_key = EXCLUDED.icon_key,
  sc_enabled = EXCLUDED.sc_enabled,
  sc_template_id = EXCLUDED.sc_template_id,
  required = EXCLUDED.required,
  upload_only = EXCLUDED.upload_only,
  multi = EXCLUDED.multi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = now();
